name: Deploy Vue.js to HostGator via SSH

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@v4
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.HOSTGATOR_HOST }}
          REMOTE_USER: ${{ secrets.HOSTGATOR_USER }}
          TARGET: ${{ secrets.HOSTGATOR_PATH }}
          SOURCE: "dist/"
